"""Static HTML target reports."""

from __future__ import annotations

import html
from pathlib import Path

import numpy as np

from .. import __version__
from .manifest import write_target_manifest


def _coordinate_rows(path: Path) -> list[list[str]]:
    try:
        values = np.loadtxt(path, ndmin=2)
    except (OSError, ValueError):
        return []
    return [[f"{value:.6f}" for value in row] for row in values]


def render_target_report(
    output_dir: str | Path,
    subject: str,
    html_path: str | Path | None = None,
) -> Path:
    """Generate an HTML report for a subject's target/FC outputs."""

    output_dir = Path(output_dir)
    subject_dir = output_dir / subject
    if not subject_dir.exists():
        raise ValueError(f"Subject directory not found: {subject_dir}")
    manifest_path = write_target_manifest(subject_dir, subject_dir / "manifest.json")

    rows: list[str] = []
    for path in sorted(subject_dir.glob("MNICoordinate_*.txt")):
        rows.append(
            "<tr>"
            f"<td>{html.escape(path.name)}</td>"
            "<td>" + "<br>".join(" ".join(row) for row in _coordinate_rows(path)) + "</td>"
            "</tr>"
        )
    coordinate_table = (
        "<table><thead><tr><th>Coordinate file</th><th>Values</th></tr></thead><tbody>"
        + "".join(rows)
        + "</tbody></table>"
        if rows
        else "<p>No MNI coordinate files found.</p>"
    )

    files = [
        path
        for path in sorted(subject_dir.rglob("*"))
        if path.is_file() and path.name != "manifest.json" and path.suffix.lower() in {".nii", ".gz", ".txt"}
    ]
    file_rows = "".join(
        f"<tr><td><a href=\"{html.escape(path.name)}\">{html.escape(path.name)}</a></td>"
        f"<td>{path.stat().st_size}</td></tr>"
        for path in files
    )

    content = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{html.escape(subject)} target report</title>
  <style>
    body {{ font-family: -apple-system, "Segoe UI", Arial, sans-serif; margin: 2rem; color: #1f2933; }}
    h1 {{ font-size: 1.4rem; }}
    table {{ border-collapse: collapse; width: 100%; margin-bottom: 1.5rem; }}
    th, td {{ border: 1px solid #d2d6dc; padding: 0.5rem; text-align: left; font-size: 0.9rem; }}
    th {{ background: #f5f7fa; }}
    code {{ background: #f5f7fa; padding: 0.1rem 0.25rem; }}
  </style>
</head>
<body>
  <h1>{html.escape(subject)} target report</h1>
  <p>Generated by neuroimaging-neuromodulation {html.escape(__version__)}.</p>
  <h2>Coordinates</h2>
  {coordinate_table}
  <h2>Output files</h2>
  <table><thead><tr><th>File</th><th>Bytes</th></tr></thead><tbody>{file_rows}</tbody></table>
  <p>Manifest: <a href="manifest.json">manifest.json</a> (SHA-256 hashes included).</p>
</body>
</html>
"""
    html_path = Path(html_path) if html_path is not None else subject_dir / "report.html"
    html_path.write_text(content, encoding="utf-8")
    return html_path


__all__ = ["render_target_report"]
